"""Generic orchestrator replay script for assembly/disassembly verification.

Assembly-agnostic: reads logged results JSON, replays every tool_sequence
entry in order, then calls signal_verify_results to check scene state.

Checkpoint support: saves scene state after each successfully replayed
object. On subsequent replays (after the agent fixes a failed object's
logs), restores the checkpoint from the last completed object and only
replays from the failed object onwards instead of replaying everything.

Usage (from execute_composed_code):
    from unified_api import *
    exec(open(os.path.join(os.environ['ROS_MCP_SERVER_DIR'], 'ablations', 'replay_verify.py')).read())
    setup_and_replay('fmb_assembly_1', 'base1', 'sim', 2)

Requires ROS_MCP_SERVER_DIR environment variable pointing to the ros-mcp-server root.

Args:
    assembly_id: e.g. 'fmb_assembly_1'
    base_name: assembly base object name
    mode: 'sim' (replay is sim-only)
    phase: 1 (disassembly) or 2 (assembly)
"""

import json
import os
import sys
from pathlib import Path


def _get_results_path(phase, assembly_id):
    """Build path to the results JSON file."""
    base = os.getenv("MCP_CLIENT_OUTPUT_DIR", "").strip()
    if not base:
        raise RuntimeError("MCP_CLIENT_OUTPUT_DIR not set")
    logs_dir = Path(base) / "logs"
    prefix = "Disassembly" if phase == 1 else "Assembly"
    return logs_dir / f"{prefix}_{assembly_id}_results.json"


def _get_rejection_path():
    """Build path to verify_rejection.json."""
    base = os.getenv("MCP_CLIENT_OUTPUT_DIR", "").strip()
    if base:
        return Path(base) / "logs" / "verify_rejection.json"
    return None


def _get_previously_completed():
    """Read completed_objects from verify_rejection.json (from prior replay)."""
    path = _get_rejection_path()
    if not path or not path.exists():
        return []
    try:
        data = json.loads(path.read_text())
        # Objects that were successfully replayed before and haven't been
        # re-rejected since. A resolved=True object was completed in a prior
        # replay and then its logs were updated -- still safe to skip.
        completed = []
        for name, state in data.get("failed_objects", {}).items():
            # Only include objects that are resolved (logs were fixed).
            # Unresolved objects need to be replayed with their new sequences.
            pass
        # Use the completed_objects list stored during the last replay
        return data.get("last_completed_objects", [])
    except (json.JSONDecodeError, OSError):
        return []


def _save_completed_objects(completed):
    """Store the list of completed objects in verify_rejection.json for next replay."""
    path = _get_rejection_path()
    if not path:
        return
    try:
        if path.exists():
            data = json.loads(path.read_text())
        else:
            data = {"failed_objects": {}}
        data["last_completed_objects"] = completed
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, indent=2))
    except (json.JSONDecodeError, OSError):
        pass


def _parse_tool_call(call_str):
    """Parse a tool call string into (function_name, kwargs).

    Input format: "ros-mcp-server__tool_name(key='value', key2='value2')"
    Output: ("ros_mcp_server__tool_name", {"key": "value", "key2": "value2"})

    Handles trailing annotations like " [FAILED]" or " [JAMMED]" that may
    appear after the closing parenthesis in logged tool sequences.
    """
    # Strip trailing annotations (e.g. " [FAILED]", " [FIRST ATTEMPT FAILED]")
    import re
    call_str = re.sub(r'\s*\[.*?\]\s*$', '', call_str)

    # Split function name from args
    paren_idx = call_str.index("(")
    raw_name = call_str[:paren_idx]
    # Find the last ')' to handle any nested parens in values
    close_paren_idx = call_str.rindex(")")
    args_str = call_str[paren_idx + 1:close_paren_idx]

    # Normalize server__tool format: hyphens -> underscores for Python
    func_name = raw_name.replace("-", "_")

    # Parse key=value pairs
    # Uses a simple approach: eval the args as keyword arguments
    # The tool_sequence entries are generated by the agent, so they follow
    # a consistent "key='value'" format
    kwargs = {}
    if args_str.strip():
        # Wrap in dict() call for safe eval
        try:
            kwargs = eval(f"dict({args_str})")
        except Exception:
            # Fallback: pass raw string, let the tool handle it
            kwargs = {"_raw_args": args_str}

    return func_name, kwargs


def setup_and_replay(assembly_id, base_name, mode, phase):
    """Robot reset + replay + verify. Convenience wrapper for gate hooks.

    Resets robot state before replaying logged sequences. Scene setup
    (new_stage, quick_start, add_objects, randomize) is handled by
    client-driven @tool-exec hooks that fire before this gate.

    If a previous replay completed some objects before failing, restores
    the checkpoint from the last completed object and skips re-replaying them.
    """
    # Check for checkpoint from a previous replay attempt
    prev_completed = _get_previously_completed()

    if prev_completed:
        # Restore scene to after the last completed object
        checkpoint_name = f"replay_checkpoint_{len(prev_completed)}.json"
        try:
            isaac_sim__restore_scene_state(json_file_path=checkpoint_name)
            ros_mcp_server__move_home(mode=mode)
            ros_mcp_server__control_gripper(command='open', mode=mode)
        except Exception:
            # Checkpoint restore failed -- fall back to full replay
            prev_completed = []
            ros_mcp_server__move_home(mode=mode)
            ros_mcp_server__control_gripper(command='open', mode=mode)
    else:
        ros_mcp_server__move_home(mode=mode)
        ros_mcp_server__control_gripper(command='open', mode=mode)

    replay(assembly_id, base_name, mode, phase, skip_objects=prev_completed)


def replay(assembly_id, base_name, mode, phase, skip_objects=None):
    """Replay logged tool sequences and verify scene state.

    Reads the results JSON, replays each object's tool_sequence in order,
    then calls signal_verify_results with the outcome.

    Args:
        skip_objects: list of object names to skip (already verified in prior replay).
    """
    if skip_objects is None:
        skip_objects = []

    # Read results
    results_path = _get_results_path(phase, assembly_id)
    if not results_path.exists():
        print(json.dumps({
            "status": "failed",
            "error": f"Results file not found: {results_path}",
        }))
        sys.exit(1)

    results = json.loads(results_path.read_text())
    order_key = "disassembly_order" if phase == 1 else "assembly_order"
    entries = sorted(results.get(order_key, []), key=lambda e: e.get(order_key, 0))

    if not entries:
        print(json.dumps({
            "status": "failed",
            "error": f"No entries in {order_key}",
        }))
        sys.exit(1)

    # Replay each object's tool sequence
    completed_objects = list(skip_objects)  # start with previously verified objects
    for entry in entries:
        object_name = entry["object_name"]
        tool_sequence = entry.get("tool_sequence", [])

        # Skip objects already verified in a prior replay
        if object_name in skip_objects:
            continue

        if not tool_sequence:
            # Disassembly entries don't have tool_sequence -- skip replay
            completed_objects.append(object_name)
            continue

        completed_steps = []  # steps that succeeded for this object
        for step in tool_sequence:
            try:
                func_name, kwargs = _parse_tool_call(step)
                # Call the tool via unified_api (available in orchestrator env)
                func = globals().get(func_name)
                if func is None:
                    raise RuntimeError(f"Unknown function: {func_name}")
                result = func(**kwargs)

                # Check for tool-level failure
                if isinstance(result, dict) and result.get("result") == "failure":
                    error_msg = result.get("error", "tool returned failure")
                    remaining = [
                        e["object_name"] for e in entries
                        if e["object_name"] not in completed_objects
                        and e["object_name"] != object_name
                    ]
                    _save_completed_objects(completed_objects)
                    replay_data = json.dumps({
                        "replay": "failure",
                        "failed_object": object_name,
                        "failed_step": step,
                        "completed_steps_for_object": completed_steps,
                        "total_steps_for_object": tool_sequence,
                        "error": error_msg,
                        "completed_objects": completed_objects,
                        "remaining_objects": remaining,
                    })
                    verify_result = ros_mcp_server__signal_verify_results(
                        phase=phase, base_name=base_name,
                        mode=mode, replay_data=replay_data,
                    )
                    print(json.dumps(verify_result))
                    sys.exit(1)

                completed_steps.append(step)

            except Exception as e:
                remaining = [
                    e_["object_name"] for e_ in entries
                    if e_["object_name"] not in completed_objects
                    and e_["object_name"] != object_name
                ]
                _save_completed_objects(completed_objects)
                replay_data = json.dumps({
                    "replay": "failure",
                    "failed_object": object_name,
                    "failed_step": step,
                    "completed_steps_for_object": completed_steps,
                    "total_steps_for_object": tool_sequence,
                    "error": str(e),
                    "completed_objects": completed_objects,
                    "remaining_objects": remaining,
                })
                verify_result = ros_mcp_server__signal_verify_results(
                    phase=phase, base_name=base_name,
                    mode=mode, replay_data=replay_data,
                )
                print(json.dumps(verify_result))
                sys.exit(1)

        completed_objects.append(object_name)

        # Save checkpoint after each successfully replayed object
        checkpoint_name = f"replay_checkpoint_{len(completed_objects)}.json"
        try:
            isaac_sim__save_scene_state(json_file_path=checkpoint_name)
        except Exception:
            pass  # Non-fatal -- just means next replay can't skip this object

    # All objects replayed successfully -- clear completed list and verify
    _save_completed_objects([])  # reset for clean state
    replay_data = json.dumps({
        "replay": "success",
        "completed_objects": completed_objects,
    })
    verify_result = ros_mcp_server__signal_verify_results(
        phase=phase, base_name=base_name,
        mode=mode, replay_data=replay_data,
    )
    print(json.dumps(verify_result))

    if isinstance(verify_result, dict) and verify_result.get("result") != "success":
        sys.exit(1)
