from typing import Annotated, Literal

from pydantic import Field
from fastmcp import FastMCP

mcp = FastMCP("Prompts")

@mcp.prompt()
def phase_1_disassembly_sequence_discovery() -> str:
    """
    Phase 1: Disassembly sequence discovery in a simulated environment.
    """
    return """**Initialization:**

Phase 1: Disassembly sequence discovery in a simulated environment.

You are an autonomous agent working in a simulation.
Identify available objects and their grasp ids. 
You will be provided the fully assembled assembly in the environment.
Save scene state.

**Task**

Your goal is to disassemble this top down assembly thereby figuring out which grasp ids and gripper states let you perform the disassembly and move them to clear space.
You can refer the instruction manual that shows the assembly steps to figure out the sequence in which you need to disassemble them.
The information you collect in this run will be used later to perform assembly.

**Execution**

Use existing tools to perform disassembly one object at a time. Understand the capabilities of the tools and the limitations of the environment.
Motion planning failed means no path to target was found — try a recovery strategy before restoring the scene.
Perform the tasks by sequentially calling individual tools to figure out a working sequence of tool calls for disassembling one object.
You can orchestrate the tools to perform a composed policy to disassemble the remaining objects once you have verified a working sequence for one object.

If an object can only be grasped using half open gripper state, then make sure you half open the gripper before moving to grasp that object. Use the same gripper state when releasing the object.
If an object can be grasped using a open gripper state and a half open gripper state, always use half open gripper state to access the object so as to not disturb other objects in the assembly when moving to grasp it from the assembly.

**Verification**

> To verify if an object was successfully disassembled: run verify disassembly once you you've ran all tools required to move one object away from the fixed base.
> 1.**SUCCESS**: verify disassembly returns success. Save scene state. Log the grasp id and gripper state using which you were able to disassemble that object. Move on to the next object.
> 2.**FAILURE**: verify disassembly returns failure. Restore scene state and try disassembling the object using a different grasp id.

**Post Execution**
Signal the client you are done with the disassembly of all objects.
"""

@mcp.prompt()
def phase_2_assembly_sequence_discovery() -> str:
    """
    Phase 2: Assembly sequence discovery in a simulated environment.
    """
    return """**Initialization:**

Phase 2: Assembly sequence discovery in a simulated environment.

You are an autonomous agent working in a simulation.
Identify available objects and their grasp ids. 
Save scene state.
Read the disassembly results (generated by disassembling a fully assembled object) to identify the grasp ids that were successfully used per object during disassembly.
Some objects may require intermediate manipulation to achieve a suitable orientation before final assembly. Any grasp id may be used during intermediate steps. However, the final step of moving the object to and inserting it into the base MUST use the grasp id from the disassembly results — this is the grasp configuration verified to achieve correct assembly.

**Task**

Your goal is to perform assembly of the objects scattered in the scene onto the base object based on the disassembly data collected earlier.
The same tool sequence might not work for all objects.

**Execution**

Read the tool descriptions properly and understand the underlying logic and sequence of the tool calls.
Motion planning failed means no path to target was found — try a recovery strategy before restoring the scene.
Use available tools to perform assembly.
DO NOT orchestrate the tools to perform a composed policy.

If an object can only be grasped using half open gripper state, then make sure you half open the gripper before moving to grasp that object. Use the same gripper state when releasing the object.
If an object can be grasped using a open gripper state and a half open gripper state, then you can use either of the gripper states to grasp the object but after assembling it into the base, use half open gripper state in order to not damage the object or disturb other assembled objects.

**Verification**

> To verify if an object was successfully assembled: run verify assembly once you you've ran all tools required to move one object into the fixed base.
> 1.**SUCCESS**: verify assembly returns success. Save scene state. Log the tools and arguments executed in sequence that worked for that object including the gripper state used.
> 2.**FAILURE**: verify assembly returns failure. Figure out if there are any steps you can take to complete the assembly. If not then restore scene state and try a different sequence you haven't tried before. 

**Post Execution**
Signal the client you are done with the assembly with an action to randomize the environment. The client will randomize the environment again so you can verify if the information you collected can be verified. 
Save scene state before you start the assembly again.
Based on the infomration you collected see if you can find any patterns in the tool calls and relate them with object properties. Your goal now is to minimize the number of tool calls to perform the assembly of the same objects again. You might have already found the minimum number of tool calls to perform the assembly of each object if not you can test your hypothesis now and perform the assemmbly.
You may also orchestrate the tools to perform a composed policy to perform the same assembly again. 
If the assembly fails, then restore scene state to try again. Update your assembly log with the new tool calls that worked.
Signal the client again once the assembly is done.
"""

@mcp.prompt()
def phase_3_perform_assembly_sequence(mode: Annotated[Literal["sim", "real"], Field(description="Environment: sim or real")]) -> str:
    """
    Phase 3: Performing Assembly in simulation or real world.
    """
    if mode == "real":
        env_description = "You are an autonomous agent working in the real world."
        setup_instruction = "Run prepare_workspace to ask a human operator to set up and verify the real workspace before starting assembly."
    else:
        env_description = "You are an autonomous agent working in a simulation."
        setup_instruction = "Identify available objects and their grasp ids."

    return f"""**Initialization:**

Phase 3: Performing Assembly ({mode} mode).

{env_description}
{setup_instruction}
Read the assembly sequence log to identify the tool call sequences for each object to perform assembly.

**Task**

You are to perform assembly of the objects onto a fixed base based on the assembly sequence resource collected using a Digital twin from your previous runs.

**Execution**

Use the available tools to perform assembly using the information of the assembly log in the same order. Do not skip any object assembly sequence.
Follow the sequence of objects and the tool calls with arguements to perform assembly one by one.

Don't orchestrate the tools to perform a composed policy. Perform the tasks using individual tools calls.

IMPORTANT: Before moving to assembly make sure the current object orietnaion is close to the target orientation. If the object fell after placing down, you might want to fix it again.

If an object can only be grasped using half open gripper state, then make sure you half open the gripper before moving to grasp that object. Use the same gripper state when releasing the object.
If an object can be grasped using a open gripper state and a half open gripper state, then you can use either of the gripper states to grasp the object but after assembling it into the base, use half open gripper state in order to not damage the object or disturb other assembled objects.

**Verification**

> To verify if an object was successfully assembled: run verify assembly once you you've ran all tools required to move one object into the fixed base.
> 1.**SUCCESS**: verify assembly returns success. Move on to the next object.
> 2.**FAILURE**: verify assembly returns failure or if any of the steps failed. Grab the object, and move to clear space and start the cycle over for that object.

**Post Execution**
Signal the client you are done with the final assembly of all objects.
"""

@mcp.prompt()
def replace_defective_part(
    object_name: Annotated[str, Field(description="Name of the defective object")],
    base_name: Annotated[str, Field(description="Name of the base assembly")],
) -> str:
    """
    An operator reports a defective part during assembly.
    """
    return f"""{object_name} assembled in {base_name} is defective. disassemble that object and place it in the clear space and notify me."""

if __name__ == "__main__":
    mcp.run()