#!/usr/bin/env python3
"""
Build the canonical RG2 URDF using per-link STL meshes + URDF top-level
material colors.

Why this approach (chosen by the operator after iteration):
- Embedded-DAE materials (UR-style) hit Lambert shading darkness on this
  asset because the source RG2.usd has per-face FLAT normals — many surfaces
  end up angled away from RViz's directional light and read as nearly black.
- URDF top-level <material><color> applied to STL meshes is the other
  ROS2 convention (used by urdf_sim_tutorial/urdf/12-gripper.urdf.xacro and
  many community URDFs). RViz applies the URDF color flat, no Lambert
  shading darkness, no embedded-material conflicts.
- The dark-circle/rectangle artifacts are gone because the STL meshes
  preserve unwelded vertices with face-winding normals that exactly match
  the source USD's authored faceVarying normals (verified empirically:
  100% alignment between face cross-products and authored normals).

The visual STL files in compliant_insertion_studio/urdf/rg2/meshes/ were
generated by the original extract_rg2_urdf.py with no welding. They contain
correct per-face flat normals. No regeneration required.

This script just rewrites rg2.urdf to use the multi-visual + top-level
material name-reference pattern with the USD-canonical colors:
  material_CCCCCC = (0.8, 0.8, 0.8) for body + all knuckles
  material_191919 = (0.1, 0.1, 0.1) for inner fingertips

Important RViz2 detail: per-visual <material> blocks with INLINE <color>
hit a documented multi-visual material bug (ros2/rviz#1293,
ros-visualization/rviz#843) where only the FIRST visual's color is honored.
The fix is to define materials at the TOP LEVEL of the URDF and reference
them by name only from each <visual>.
"""
from pathlib import Path
from xml.etree import ElementTree as ET

REPO = Path("/home/aaugus11/Documents/ros-mcp-server")
OUT_DIR = REPO / "compliant_insertion_studio" / "urdf" / "rg2"
OUT_URDF = OUT_DIR / "rg2.urdf"

# (visual_stl, collision_stl, xyz, rpy, material_name)
PARTS = [
    ("base_visual.stl",        "base_collision.stl",
     (0.000000, -0.000000, 0.000000), (0.0, -0.0, -1.570797), "rg2_grey"),
    ("lo_knuckle_visual.stl",  "lo_knuckle_collision.stl",
     (-0.017180, -0.000000, 0.125800), (0.0, -0.0, -1.570797), "rg2_grey"),
    ("li_knuckle_visual.stl",  "li_knuckle_collision.stl",
     (-0.007680, -0.000000, 0.142300), (0.0, -0.0, -1.570797), "rg2_grey"),
    ("l_finger_visual.stl",    "l_finger_collision.stl",
     (-0.056770,  0.000000, 0.163970), (0.0, -0.0, -1.570797), "rg2_dark"),
    ("ro_knuckle_visual.stl",  "ro_knuckle_collision.stl",
     ( 0.017180, -0.000000, 0.125800), (0.0,  0.0,  1.570797), "rg2_grey"),
    ("ri_knuckle_visual.stl",  "ri_knuckle_collision.stl",
     ( 0.007680, -0.000000, 0.142300), (0.0,  0.0,  1.570796), "rg2_grey"),
    ("r_finger_visual.stl",    "r_finger_collision.stl",
     ( 0.056770,  0.000000, 0.163970), (0.0,  0.0,  1.570797), "rg2_dark"),
]
MATERIALS = {
    "rg2_grey": (0.800, 0.800, 0.800, 1.0),
    "rg2_dark": (0.100, 0.100, 0.100, 1.0),
}


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    robot = ET.Element("robot", {"name": "rg2"})

    # Top-level material defs (must be before <link> so RViz parses them
    # before resolving link material references by name).
    for name, rgba in MATERIALS.items():
        m = ET.SubElement(robot, "material", {"name": name})
        ET.SubElement(m, "color", {"rgba": " ".join(f"{c:.3f}" for c in rgba)})

    link = ET.SubElement(robot, "link", {"name": "rg2_base_link"})

    inertial = ET.SubElement(link, "inertial")
    ET.SubElement(inertial, "origin", {"xyz": "0 0 0.1", "rpy": "0 0 0"})
    ET.SubElement(inertial, "mass", {"value": "0.78"})  # OnRobot RG2 ≈ 780 g
    ET.SubElement(
        inertial, "inertia",
        {"ixx": "1e-3", "ixy": "0", "ixz": "0",
         "iyy": "1e-3", "iyz": "0", "izz": "1e-3"},
    )

    for vis_stl, col_stl, xyz, rpy, mat_name in PARTS:
        v = ET.SubElement(link, "visual")
        ET.SubElement(v, "origin", {
            "xyz": f"{xyz[0]:.6f} {xyz[1]:.6f} {xyz[2]:.6f}",
            "rpy": f"{rpy[0]:.6f} {rpy[1]:.6f} {rpy[2]:.6f}",
        })
        g = ET.SubElement(v, "geometry")
        ET.SubElement(g, "mesh", {
            "filename": f"package://compliant_insertion_studio/urdf/rg2/meshes/{vis_stl}",
            "scale": "1 1 1",
        })
        # By-name reference only (no inline <color>).
        ET.SubElement(v, "material", {"name": mat_name})

        c = ET.SubElement(link, "collision")
        ET.SubElement(c, "origin", {
            "xyz": f"{xyz[0]:.6f} {xyz[1]:.6f} {xyz[2]:.6f}",
            "rpy": f"{rpy[0]:.6f} {rpy[1]:.6f} {rpy[2]:.6f}",
        })
        gc = ET.SubElement(c, "geometry")
        ET.SubElement(gc, "mesh", {
            "filename": f"package://compliant_insertion_studio/urdf/rg2/meshes/{col_stl}",
            "scale": "1 1 1",
        })

    ET.indent(robot, space="  ")
    ET.ElementTree(robot).write(OUT_URDF, encoding="utf-8", xml_declaration=True)
    print(f"Wrote {OUT_URDF.relative_to(REPO)}")
    print(f"  {len(PARTS)} visuals + {len(PARTS)} collisions")
    print(f"  {len(MATERIALS)} top-level materials")


if __name__ == "__main__":
    main()
